name: Build documentation

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system
  DISPLAY: ":99.0"
  CI: 1

jobs:

  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/finsberg/ftfetwild-meta:main
    env:
      PUBLISH_DIR: ./_build/html
      DISPLAY: ":99.0"
      PYVISTA_TRAME_SERVER_PROXY_PREFIX: "/proxy/"
      PYVISTA_TRAME_SERVER_PROXY_ENABLED: "True"
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: "html"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: python3 -m pip install ".[docs]"

      - name: Build docs
        run: jupyter book build -W --keep-going .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}
