name: Build documentation

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

env:
  HDF5_MPI: "ON"
  HDF5_DIR: "/usr/local/"
  DISPLAY: ":99.0"
  DEB_PYTHON_INSTALL_LAYOUT: deb_system
  LIBGL_ALWAYS_SOFTWARE: 1

jobs:

  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/fenics/dolfinx/lab:stable
    env:
      PUBLISH_DIR: ./_build/html
      PYVISTA_TRAME_SERVER_PROXY_PREFIX: "/proxy/"
      PYVISTA_TRAME_SERVER_PROXY_ENABLED: "True"
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: "html"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies for pyvista
        run: apt-get update && apt-get install -y libxrender1 xvfb

      - name: Install dependencies
        run: python3 -m pip install ".[docs]"

      - name: Build docs
        run: jupyter book build -W --keep-going .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}
