name: Build documentation

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system
  DISPLAY: ":99.0"
  CI: 1

jobs:

  build:
    runs-on: ubuntu-22.04
    env:
      PUBLISH_DIR: ./_build/html
      DISPLAY: ":99.0"
      PYVISTA_TRAME_SERVER_PROXY_PREFIX: "/proxy/"
      PYVISTA_TRAME_SERVER_PROXY_ENABLED: "True"
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: "html"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies for pyvista
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xvfb

      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          channels: conda-forge,defaults
          channel-priority: strict
          activate-environment: mri2mesh
          environment-file: environment.yml
          miniforge-version: latest

      - name: Install dependencies
        run: python3 -m pip install ".[docs]"

      - name: Build docs
        run: jupyter book build -W --keep-going .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}
